version: 2.1

jobs:
    checkout:
        docker:
        - image: cimg/openjdk:17.0.13
        steps:
          - checkout
          - run: java --version

workflows:
    regards:
        jobs:
        - checkout