version: 2.1

executors:
    base:
        docker:
        - image: justb4/jmeter:latest
            
jobs:
    run-jmeter-test:
        executor: base
        steps:
            - checkout
            - run: 
                name: Run JMeter
                command: |
                    mkdir -p results
                    jmeter -n -t jmeter-test.jmx -l results/results.jtl -e -o results/report
            - store_artifacts:
                path: results
                destination: jmeter-results
            - store_test_results:
               path: results
workflows:
    regards:
        jobs:
        - run-jmeter-test