version: 2.1

executors:
    base:
        docker:
        - image: cimg/openjdk:17.0.3
        working_directory: ~/app
jobs:
    run-jmeter-test:
        executor: base
        steps:
            - checkout
            - run:
                name: Install JMeter 
                command: |
                    curl -O https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.6.3.tgz
                    tar -xzf apache-jmeter-5.6.3.tgz
                    export PATH=~/app/apache-jmeter-5.6.3/bin:$PATH
            - run: 
                name: Run JMeter
                command: |
                    jmeter -n -t jmeter-test.jmx -l results/results.jtl -e -o results/report
            - store_artifacts:
                path: results
                destination: jmeter-results
            - store_test_results:
               path: results
workflows:
    regards:
        jobs:
        - run-jmeter-test