version: 2.1

jobs:
    build1:
        docker:
        - image: cimg/base:2022.05    
        steps:
        - run: echo "Hello, T-EVOLERS ONE!"
    build2:
        docker:
        - image: cimg/base:2022.05    
        steps:
        - run: echo "Hello, T-EVOLERS TWO!"   

workflows:
    regards:
        jobs:
        - build1
        - build2