version: 2.1

executors:
    base:
        docker:
        - image: justb4/jmeter
        working_directory: ~/app
            
jobs:
    run-jmeter-test:
        executor: base
        steps:
            - checkout
            - run:
                name: Instalar JMeter Plugin Manager 
                command: |
                    wget https://jmeter-plugins.org/get/ -O /opt/jmeter/lib/ext/jmeter-plugins-manager.jar
                    java -cp /opt/jmeter/lib/ext/jmeter-plugins-manager.jar org.jmeterplugins.repository.PluginManagerCMDInstaller
            - run:
                 name: Instalar Plugins TST
                 command: |
                     java -cp /opt/jmeter/lib/ext/jmeter-plugins-manager.jar org.jmeterplugins.repository.PluginManagerCMD install jpgc-casutg
            - run: 
                name: Run JMeter
                command: |
                    mkdir -p results
                    jmeter -n -t jmeter-test.jmx -l results/results.jtl -e -o results/report
            - store_artifacts:
                path: results
                destination: jmeter-results
            - store_test_results:
               path: results
workflows:
    regards:
        jobs:
        - run-jmeter-test